--PRODUCT_ID : 상품아이디 (고유한 아이디므로 PRIMARY KEY 제약조건) 
--P_NAME : 상품명 (값이 무조건 있어야 되므로 NOT NULL 제약조건) 
--PRICE : 상품가격 (값이 무조건 있어야 되므로 NOT NULL 제약조건) 
--DESCRIPTION : 상품상세정보  
-- STOCK : 재고 (값이 무조건 있어야 되므로 NOT NULL 제약조건) 

DROP TABLE PRODUCT;


CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(10) PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(30),
    STOCK NUMBER NOT NULL
);

COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품 아이디';
COMMENT ON COLUMN PRODUCT.P_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT.PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.DESCRIPTION IS '상품상세정보';
COMMENT ON COLUMN PRODUCT.STOCK IS '재고';

INSERT INTO PRODUCT VALUES ('nb_ss7','삼성노트북',1570000,'시리즈7',10);
INSERT INTO PRODUCT VALUES ('nb_ama4','맥북에어',1200000,'xcode4',20);
INSERT INTO PRODUCT VALUES ('pc_ibm','ibmPC',750000,'window8',5);

commit;


