


DROP SEQUENCE SEQ_BNO;
DROP TABLE TB_CATEGORY;
DROP TABLE TB_BOOK;


CREATE SEQUENCE SEQ_BNO
START WITH 1
INCREMENT BY 1;

CREATE TABLE TB_CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30)
);

INSERT INTO TB_CATEGORY VALUES(1, '인문');
INSERT INTO TB_CATEGORY VALUES(2, '자연과학');
INSERT INTO TB_CATEGORY VALUES(3, '의료');
INSERT INTO TB_CATEGORY VALUES(4, '기타');



CREATE TABLE TB_BOOK (
    BNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(30) NOT NULL,
    CATEGORY NUMBER NOT NULL,
    AUTHOR VARCHAR2(20) NOT NULL,
   CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NO)
);





-- 도서 삽입 SQL
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'백종원의 집밥',4,'백종원');
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'한번 더 해요',3,'미티');
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'루피의 원피스',2,'루피');
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'최현석 날 따라해봐',1,'최현석');
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'얼마나 맛있게요',2,'이혜정');
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'루피의 바다',2,'루피');

COMMIT;

--
---- 도서 삭제 sql
--DELETE FROM TB_BOOK;
--
---- 도서 검색 sql
SELECT * FROM TB_BOOK WHERE TITLE LIKE '%' || '루피' || '%';
--
----  도서 목록 조회 sql;
--SELECT * FROM TB_BOOK;
--
---- 카테고리로 도서 조회 sql;
SELECT BNO, TITLE, CATEGORY, AUTHOR 
FROM TB_BOOK 
JOIN TB_CATEGORY  ON(CATEGORY = CATEGORY_NO)
WHERE CATEGORY_NAME = '인문';